#!/usr/bin/env bash
# Loops 1-10 and disapalays bad luck on 4th loop and goodluck on8th loop
i=1
while [ $i -le 10 ]
do
      if [ $i -eq 4 ];
      then
           echo "bad luck"

      elif [ $i -eq 8 ];
      then
          echo "good luck"
      else
           echo "Best School"
      fi
      ((i++))
 done