#!/usr/bin/env bash
# bash script that display number from 1 to 20 and use phrases
i=1
while [ $i -le 20 ]
do
echo $i
case $i in
     4
     echo " bad luck from China"
     ;;

     9)
     echo "bad luck from Japan"
     ;;

     17)
     echo "bad luck from italy"
     ;;
esac
    ((i++))
done