#!/usr/bin/env bash
# displays the times for 12 hours and 59 mintues:

i=0
j=1
while [ $i -le 12 ]
do
    echo "Hour: $i"
    j=1
    ((i++))
    while [ $j -le 59 ]
    do
       echo $j
       ((j++))
       done
done